version: '3.4'

services:
 
  devopschallenge.salesapi:
    image: srajput81/devopschallengesalesapi:latest
    tty: true
    environment:   
      - CONNECTIONSTRINGS__DATABASE=Server=$DB_SERVER;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASSWORD 
    ports:
          - "$API_PORT:80" 
    build:
      context: .
      dockerfile: src/DevOpsChallenge.SalesApi/Dockerfile
    depends_on:  
      - devopschallenge.migrations
      - devopschallenge.db   
    volumes: 
      - ./logs/xunit:/var/temp 

  devopschallenge.db:  
    image: mcr.microsoft.com/mssql/server:2019-latest  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "$DB_PASSWORD"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - "$DB_PORT:1433" 
    expose:  
      - 1433   

  devopschallenge.migrations:
    image: srajput81/saleapimigrations:latest 
    build: 
      context: .
      dockerfile: src/DevOpsChallenge.SalesApi.Database/Dockerfile 
    environment:  
     - CONNECTIONSTRINGS__DATABASE=Server=$DB_SERVER;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASSWORD 
    depends_on: 
      - devopschallenge.db 