version: '3.4'

services:
 
  devopschallenge.salesapi:
    image: srajput81/devopschallengesalesapi:latest
    tty: true
    environment:   
      - CONNECTIONSTRINGS__DATABASE=Server=$DB_SERVER;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASSWORD 
    ports:
          - "$API_PORT:80"
   

  devopschallenge.db:  
    image: mcr.microsoft.com/mssql/server:2019-latest  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "$DB_PASSWORD"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
       - "$DB_PORT:1433" 
    expose:  
      - 1433     

  
  devopschallenge.migrations:
    image: srajput81/saleapimigrations:latest 
    environment:  
      - CONNECTIONSTRINGS__DATABASE=Server=$DB_SERVER;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASSWORD 
    depends_on: 
      - devopschallenge.db 

  devopschallenge.integrationtests:  
    image: srajput81/saleapiintegrations:latest 
    build:  
      context: .  
      dockerfile: tests/DevOpsChallenge.SalesApi.IntegrationTests/Dockerfile 
    environment:  
      - SALES_API_ENDPOINT=$SALES_API_ENDPOINT 
    healthcheck:
        test: ["CMD", "curl", "-f", "$SALES_API_ENDPOINT"]
        interval: 5s
        timeout: 5s
        retries: 10
    volumes:
      - /opt/vsts/work/_temp:/var/temp