version: '3.4'

services:
  devopschallenge.salesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80" 
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro