version: '3.4'

services:
 
  devopschallenge.salesapi:
    image: srajput81/devopschallengesalesapi:latest
    tty: true
    environment:   
      - CONNECTIONSTRINGS__DATABASE=Server=sqlserver;Database=DevOpsChallenge.SalesApi;User Id=sa;Password=S3curePassw0rd! 
    ports:
          - "8000:80"  
   

  devopschallenge.db:  
    image: mcr.microsoft.com/mssql/server:2019-latest  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "S3curePassw0rd!"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  
    expose:  
      - 1433     

  
  devopschallenge.migrations:
    image: srajput81/saleapimigrations:latest 
    environment:  
      - CONNECTIONSTRINGS__DATABASE=Server=sqlserver;Database=DevOpsChallenge.SalesApi;User Id=sa;Password=S3curePassw0rd! 
    depends_on: 
      - devopschallenge.db 

  devopschallenge.integrationtests:  
    image: srajput81/saleapiintegrations:latest 
    build:  
      context: .  
      dockerfile: tests/DevOpsChallenge.SalesApi.IntegrationTests/Dockerfile 
    environment:  
      - SALES_API_ENDPOINT=http://devopschallenge.salesapi:80/
      - CONNECTIONSTRINGS__DATABASE=Server=sqlserver;Database=DevOpsChallenge.SalesApi;User Id=sa;Password=S3curePassw0rd! 
    healthcheck:
        test: ["CMD", "curl", "-f", "http://devopschallenge.salesapi:80"]
        interval: 5s
        timeout: 5s
        retries: 10
    volumes:
      - /opt/vsts/work/_temp:/var/temp